//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRESTAMOSYA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_Cobrar
    {
        public int ID_Cuenta_Cobrar { get; set; }
        public int ID_Cliente { get; set; }
        public decimal Total_Mora { get; set; }
        public decimal Monto_Capital { get; set; }
        public decimal Monto_Interes { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
