//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRESTAMOSYA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public int ID_Recibo { get; set; }
        public int ID_Cliente { get; set; }
        public decimal Monto { get; set; }
        public string Tipo_Pago { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ID_Transaccion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
