//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRESTAMOSYA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitude
    {
        public int ID_Solicitud { get; set; }
        public int ID_Cliente { get; set; }
        public string Nombre_Solicitante { get; set; }
        public string Telefono_Solicitante { get; set; }
        public decimal tasa { get; set; }
        public decimal monto { get; set; }
        public string plazo { get; set; }
        public decimal Monto_Cuota { get; set; }
        public string Correo_Electronico { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
